  - name: Packagist Update
  # You may pin to the exact commit or the version.
  # uses: mnavarrocarter/packagist-update@72b6a490902b9e14e114dd748b112bb49087c642
  uses: mnavarrocarter/packagist-update@v1.0.0
  with:
    # The packagist domain to call.
    # domain: # optional, default is packagist.org
    # Your packagist username
    username: gp10devhts
    # Your packagist api token
    api_token: 
    # Your package name (vendor/name). If not present, it takes it from composer.json
    # package_name: gp10devhts/ug-village-locations
          
